/** UI/domain types — data always comes from the API (see `lib/data.ts`). */
export type {
  Order,
  Shipment,
  ShipmentMilestone,
  SourcingRequest,
  SourcingAttachment,
  SourcingQuoteReceived,
  SourcingRequestDetail,
  UserSourcingRequestDetail,
  UserSourcingRequestItem,
  ExploreCategory,
  MarketplaceProduct,
  AdminCategoryCard,
  AdminInventoryItem,
  AdminInventoryKpis,
  AdminDashboardKpis,
  DashboardSourcingRow,
  LogisticsPipelineCard,
  SourcingOrderRow,
  AdminMarketplaceOrderRow,
  UserMarketplaceOrder,
  UserMarketplaceOrderDetail,
  Product,
  RelatedProduct,
  InventoryCatalogItem,
} from './domain-types';
